version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '9292:9292'
      - '8080:8080'
    volumes:
      - .:/usr/src/bookman
      - ./vendor/bundle:/usr/local/bundle
